In [3]:
import numpy as np
import pandas as pd

In [4]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1, type(arr1))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [5]:
arr2 = np.array([1,2,3,4,5], dtype=float)
print(arr2, type(arr2))

[1. 2. 3. 4. 5.] <class 'numpy.ndarray'>


In [6]:
arr3 = np.array([[1,2], [3,4]])
print(arr3)

[[1 2]
 [3 4]]


In [7]:
np.arange(1, 20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [8]:
np.linspace(1, 10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [9]:
np.zeros([1,2])

array([[0., 0.]])

In [12]:
[i+1 for i in range(10)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [15]:
ser1 = pd.Series([1,2,3,4,5], index=['a', 'b', 'c', 'd', 'e'])
print(ser1, type(ser1))

a    1
b    2
c    3
d    4
e    5
dtype: int64 <class 'pandas.core.series.Series'>


In [16]:
print(ser1.values)

[1 2 3 4 5]
